# Generated by Django 4.0 on 2021-12-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='followed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
